/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of Fast.xs. Do not edit this file, edit Fast.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "Fast.xs"
#include "common.h"
#include "tools.h"

#line 14 "Fast.c"
XS(XS_Devel__LeakTrace__Fast__hook_runops); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__LeakTrace__Fast__hook_runops)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Devel::LeakTrace::Fast::_hook_runops()");
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 11 "Fast.xs"
{
    tools_hook_runops();
}
#line 28 "Fast.c"
	PUTBACK;
	return;
    }
}

XS(XS_Devel__LeakTrace__Fast__reset_counters); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__LeakTrace__Fast__reset_counters)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Devel::LeakTrace::Fast::_reset_counters()");
   PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 18 "Fast.xs"
{
    tools_reset_counters();
}
#line 47 "Fast.c"
	PUTBACK;
	return;
    }
}

XS(XS_Devel__LeakTrace__Fast__show_used); /* prototype to pass -Wmissing-prototypes */
XS(XS_Devel__LeakTrace__Fast__show_used)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: Devel::LeakTrace::Fast::_show_used()");
    {
#line 25 "Fast.xs"
{
    tools_show_used();
}
#line 64 "Fast.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_Devel__LeakTrace__Fast); /* prototype to pass -Wmissing-prototypes */
XS(boot_Devel__LeakTrace__Fast)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("Devel::LeakTrace::Fast::_hook_runops", XS_Devel__LeakTrace__Fast__hook_runops, file, "");
        newXSproto("Devel::LeakTrace::Fast::_reset_counters", XS_Devel__LeakTrace__Fast__reset_counters, file, "");
        newXSproto("Devel::LeakTrace::Fast::_show_used", XS_Devel__LeakTrace__Fast__show_used, file, "");
    XSRETURN_YES;
}

